import Header from "@/Components/Header/Header";
import "./globals.css";


export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />  
        {children}
      </body>
    </html>
  );
}