import Header from "@/components/Header/Header";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import Stats from "@/Components/Stats/Stats";


export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Header />  
        <Stats></Stats>
        {children}
        <Footer/>
      </body>
    </html>
  );
}